(set-register ?x '(file . "~/.xbindkeysrc.scm"))
(set-register ?i '(file . "~/.emacs.d/init.el"))
(set-register ?r '(file . "~/.emacs.d/phil/registers.el"))
(set-register ?h '(file . "~/.ssh/known_hosts"))
(set-register ?m '(file . "~/.xmonad/xmonad.hs"))
(set-register ?p '(file . "~/.polywell/init.lua"))
(set-register ?k '(file . "~/.keysnail.js"))
(set-register ?a '(file . "~/.dotfiles/awesomerc.lua"))
(set-register ?l '(file . "~/.lein/profiles.clj"))

