(set-register ?n '(file . "~/.dotfiles/.notes.org"))
(set-register ?i '(file . "~/.emacs.d/init.el"))
(set-register ?r '(file . "~/.emacs.d/phil/registers.el"))
(set-register ?w '(file . "~/.emacs.d/phil/wm.el"))
(set-register ?h '(file . "~/.ssh/known_hosts"))
