;;; My general personalizations

;; Random stuff

(package-initialize)

(require 'cl)

(setq custom-file (expand-file-name "~/.emacs.d/custom.el")
      ispell-extra-args '("--keyboard=dvorak")
      ido-use-virtual-buffers t
      org-default-notes-file "~/.dotfiles/.notes.org"
      org-remember-default-headline 'bottom
      org-completion-use-ido t
      epa-armor t
      tls-checktrust 'ask
      el-get-allow-insecure nil
      gnutls-verify-error t
      network-security-level 'high
      inhibit-startup-message t
      uniquify-buffer-name-style 'post-forward
      browse-url-browser-function 'browse-url-firefox
      ;; M-x project-find-file doesn't ido without this
      mastodon-instance-url "https://icosahedron.website"
      ido-ubiquitous-allow-on-functional-collection t)

(when window-system
  (setq scroll-conservatively 1))

;; Instead of using package.el, I pull specific verisons of packages
;; in using git subtree, but this means I need to set up autoloads myself.
(dolist (l (directory-files (concat user-emacs-directory "lib") nil "^[^\.]"))
  (message "Adding load-path %s" l)
  (add-to-list 'load-path (concat user-emacs-directory "lib/" l))
  (autoload (intern l) (concat l ".el")))

;; TODO: add subtrees for smex, yaml-mode, paredit, ido-ubiquitous, markdown-mode

(add-to-list 'load-path (concat user-emacs-directory "/phil/../"))
;; The autoloads from lib/ are generated by pnh-reinit-libs in phil/bootstrap.el
(load (concat user-emacs-directory "my-autoload.el") t)
(load custom-file t)

;; personal stuff
(mapc 'load (directory-files (concat user-emacs-directory user-login-name)
                             t "^[^#].*el$"))

(setq custom-theme-load-path
      (directory-files (concat user-emacs-directory "themes") t "^[^\.]"))

(when (require 'smex nil t)
  (smex-initialize)
  (global-set-key (kbd "M-x") 'smex))

(defalias 'yes-or-no-p 'y-or-n-p)

(column-number-mode t)

(winner-mode)

(ido-ubiquitous-mode t)

(eval-after-load 'markdown-mode
  (progn (add-hook 'markdown-mode-hook 'flyspell-mode)
         (add-hook 'markdown-mode-hook 'auto-fill-mode)))

(add-hook 'text-mode-hook 'flyspell-mode)
(add-hook 'text-mode-hook 'auto-fill-mode)

(add-to-list 'load-path "~/src/circleci.el")
(autoload 'circleci "circleci.el" nil t)

(defun uuid ()
  (interactive)
  (insert (shell-command-to-string "uuid -v 4")))

;; why not?
(eshell)
;; graaaaaaah! eshell doesn't respect eval-after-load for some reason:
(with-current-buffer "*eshell*" (setq pcomplete-cycle-completions nil))
(set-face-foreground 'eshell-prompt "turquoise")
(put 'upcase-region 'disabled nil)

;; Mitigate Bug#28350 (security) in Emacs 25.2 and earlier.
(eval-after-load "enriched"
  '(defun enriched-decode-display-prop (start end &optional param)
     (list start end)))
